# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.srcs/sources_1/bd/network_clock/ip/network_clock_axi_gpio_0_3/network_clock_axi_gpio_0_3.xci
# IP: The module: 'network_clock_axi_gpio_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_gpio_0_3/network_clock_axi_gpio_0_3_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'network_clock_axi_gpio_0_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_gpio_0_3/network_clock_axi_gpio_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'network_clock_axi_gpio_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_gpio_0_3/network_clock_axi_gpio_0_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'network_clock_axi_gpio_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.srcs/sources_1/bd/network_clock/ip/network_clock_axi_gpio_0_3/network_clock_axi_gpio_0_3.xci
# IP: The module: 'network_clock_axi_gpio_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_gpio_0_3/network_clock_axi_gpio_0_3_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'network_clock_axi_gpio_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_gpio_0_3/network_clock_axi_gpio_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'network_clock_axi_gpio_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_gpio_0_3/network_clock_axi_gpio_0_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'network_clock_axi_gpio_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
