# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.srcs/sources_1/bd/network_clock/ip/network_clock_axi_ethernet_0_0/network_clock_axi_ethernet_0_0.xci
# IP: The module: 'network_clock_axi_ethernet_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_ethernet_0_0/bd_0/bd_ae0d.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ae0d || ORIG_REF_NAME==bd_ae0d} -quiet] -quiet

# IP: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_ethernet_0_0/bd_0/ip/ip_0/bd_ae0d_eth_buf_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ae0d_eth_buf_0 || ORIG_REF_NAME==bd_ae0d_eth_buf_0} -quiet] -quiet

# IP: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_ethernet_0_0/bd_0/ip/ip_1/bd_ae0d_mac_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ae0d_mac_0 || ORIG_REF_NAME==bd_ae0d_mac_0} -quiet] -quiet

# IP: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_ethernet_0_0/bd_0/ip/ip_2/bd_ae0d_c_shift_ram_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ae0d_c_shift_ram_0_0 || ORIG_REF_NAME==bd_ae0d_c_shift_ram_0_0} -quiet] -quiet

# IP: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_ethernet_0_0/bd_0/ip/ip_3/bd_ae0d_c_counter_binary_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ae0d_c_counter_binary_0_0 || ORIG_REF_NAME==bd_ae0d_c_counter_binary_0_0} -quiet] -quiet

# IP: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_ethernet_0_0/bd_0/ip/ip_4/bd_ae0d_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ae0d_xlconstant_0_0 || ORIG_REF_NAME==bd_ae0d_xlconstant_0_0} -quiet] -quiet

# IP: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_ethernet_0_0/bd_0/ip/ip_5/bd_ae0d_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ae0d_util_vector_logic_0_0 || ORIG_REF_NAME==bd_ae0d_util_vector_logic_0_0} -quiet] -quiet

# XDC: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_ethernet_0_0/bd_0/bd_ae0d_ooc.xdc

# XDC: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_ethernet_0_0/network_clock_axi_ethernet_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'network_clock_axi_ethernet_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_ethernet_0_0/synth/network_clock_axi_ethernet_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'network_clock_axi_ethernet_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_ethernet_0_0/synth/network_clock_axi_ethernet_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'network_clock_axi_ethernet_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.srcs/sources_1/bd/network_clock/ip/network_clock_axi_ethernet_0_0/network_clock_axi_ethernet_0_0.xci
# IP: The module: 'network_clock_axi_ethernet_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_ethernet_0_0/bd_0/bd_ae0d.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ae0d || ORIG_REF_NAME==bd_ae0d} -quiet] -quiet

# IP: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_ethernet_0_0/bd_0/ip/ip_0/bd_ae0d_eth_buf_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ae0d_eth_buf_0 || ORIG_REF_NAME==bd_ae0d_eth_buf_0} -quiet] -quiet

# IP: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_ethernet_0_0/bd_0/ip/ip_1/bd_ae0d_mac_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ae0d_mac_0 || ORIG_REF_NAME==bd_ae0d_mac_0} -quiet] -quiet

# IP: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_ethernet_0_0/bd_0/ip/ip_2/bd_ae0d_c_shift_ram_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ae0d_c_shift_ram_0_0 || ORIG_REF_NAME==bd_ae0d_c_shift_ram_0_0} -quiet] -quiet

# IP: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_ethernet_0_0/bd_0/ip/ip_3/bd_ae0d_c_counter_binary_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ae0d_c_counter_binary_0_0 || ORIG_REF_NAME==bd_ae0d_c_counter_binary_0_0} -quiet] -quiet

# IP: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_ethernet_0_0/bd_0/ip/ip_4/bd_ae0d_xlconstant_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ae0d_xlconstant_0_0 || ORIG_REF_NAME==bd_ae0d_xlconstant_0_0} -quiet] -quiet

# IP: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_ethernet_0_0/bd_0/ip/ip_5/bd_ae0d_util_vector_logic_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_ae0d_util_vector_logic_0_0 || ORIG_REF_NAME==bd_ae0d_util_vector_logic_0_0} -quiet] -quiet

# XDC: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_ethernet_0_0/bd_0/bd_ae0d_ooc.xdc

# XDC: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_ethernet_0_0/network_clock_axi_ethernet_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'network_clock_axi_ethernet_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_ethernet_0_0/synth/network_clock_axi_ethernet_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'network_clock_axi_ethernet_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_ethernet_0_0/synth/network_clock_axi_ethernet_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'network_clock_axi_ethernet_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
