# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Data/en.525.612/Parlak_Project/hardware/Nexys-A7-100T-Master.xdc

# Block Designs: bd/network_clock/network_clock.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock || ORIG_REF_NAME==network_clock} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_mig_7series_0_0/network_clock_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_mig_7series_0_0 || ORIG_REF_NAME==network_clock_mig_7series_0_0} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_clk_wiz_0_0/network_clock_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_clk_wiz_0_0 || ORIG_REF_NAME==network_clock_clk_wiz_0_0} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_microblaze_0_0/network_clock_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_microblaze_0_0 || ORIG_REF_NAME==network_clock_microblaze_0_0} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_dlmb_v10_0/network_clock_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_dlmb_v10_0 || ORIG_REF_NAME==network_clock_dlmb_v10_0} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_ilmb_v10_0/network_clock_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_ilmb_v10_0 || ORIG_REF_NAME==network_clock_ilmb_v10_0} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_dlmb_bram_if_cntlr_0/network_clock_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==network_clock_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_ilmb_bram_if_cntlr_0/network_clock_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==network_clock_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_lmb_bram_0/network_clock_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_lmb_bram_0 || ORIG_REF_NAME==network_clock_lmb_bram_0} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_xbar_0/network_clock_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_xbar_0 || ORIG_REF_NAME==network_clock_xbar_0} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_microblaze_0_axi_periph_0/network_clock_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_microblaze_0_axi_periph_0 || ORIG_REF_NAME==network_clock_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_microblaze_0_axi_intc_0/network_clock_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_microblaze_0_axi_intc_0 || ORIG_REF_NAME==network_clock_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_microblaze_0_xlconcat_0/network_clock_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_microblaze_0_xlconcat_0 || ORIG_REF_NAME==network_clock_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_mdm_1_0/network_clock_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_mdm_1_0 || ORIG_REF_NAME==network_clock_mdm_1_0} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_rst_clk_wiz_0_100M_0/network_clock_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==network_clock_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_axi_timer_0_0/network_clock_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_axi_timer_0_0 || ORIG_REF_NAME==network_clock_axi_timer_0_0} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_proc_sys_reset_0_0/network_clock_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_proc_sys_reset_0_0 || ORIG_REF_NAME==network_clock_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_xbar_1/network_clock_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_xbar_1 || ORIG_REF_NAME==network_clock_xbar_1} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_axi_interconnect_0_0/network_clock_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_axi_interconnect_0_0 || ORIG_REF_NAME==network_clock_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_axi_uartlite_0_0/network_clock_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_axi_uartlite_0_0 || ORIG_REF_NAME==network_clock_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_mii_to_rmii_0_1/network_clock_mii_to_rmii_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_mii_to_rmii_0_1 || ORIG_REF_NAME==network_clock_mii_to_rmii_0_1} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_axi_ethernet_0_0/network_clock_axi_ethernet_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_axi_ethernet_0_0 || ORIG_REF_NAME==network_clock_axi_ethernet_0_0} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_axi_ethernet_0_fifo_0/network_clock_axi_ethernet_0_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_axi_ethernet_0_fifo_0 || ORIG_REF_NAME==network_clock_axi_ethernet_0_fifo_0} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_axi_gpio_0_3/network_clock_axi_gpio_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_axi_gpio_0_3 || ORIG_REF_NAME==network_clock_axi_gpio_0_3} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_xlslice_0_0/network_clock_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_xlslice_0_0 || ORIG_REF_NAME==network_clock_xlslice_0_0} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_xlslice_0_1/network_clock_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_xlslice_0_1 || ORIG_REF_NAME==network_clock_xlslice_0_1} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_xlslice_0_2/network_clock_xlslice_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_xlslice_0_2 || ORIG_REF_NAME==network_clock_xlslice_0_2} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_xlslice_2_0/network_clock_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_xlslice_2_0 || ORIG_REF_NAME==network_clock_xlslice_2_0} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_xlslice_1_0/network_clock_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_xlslice_1_0 || ORIG_REF_NAME==network_clock_xlslice_1_0} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_xlslice_1_1/network_clock_xlslice_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_xlslice_1_1 || ORIG_REF_NAME==network_clock_xlslice_1_1} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_xlslice_1_2/network_clock_xlslice_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_xlslice_1_2 || ORIG_REF_NAME==network_clock_xlslice_1_2} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_xlslice_1_3/network_clock_xlslice_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_xlslice_1_3 || ORIG_REF_NAME==network_clock_xlslice_1_3} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_seg7_display_0_1/network_clock_seg7_display_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_seg7_display_0_1 || ORIG_REF_NAME==network_clock_seg7_display_0_1} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_auto_us_0/network_clock_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_auto_us_0 || ORIG_REF_NAME==network_clock_auto_us_0} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_auto_us_1/network_clock_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_auto_us_1 || ORIG_REF_NAME==network_clock_auto_us_1} -quiet] -quiet

# IP: bd/network_clock/ip/network_clock_auto_cc_0/network_clock_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==network_clock_auto_cc_0 || ORIG_REF_NAME==network_clock_auto_cc_0} -quiet] -quiet

# XDC: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/network_clock_ooc.xdc
