# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_ae0d_mac_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ae0d_mac_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_ae0d_mac_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ae0d_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_ae0d_mac_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ae0d_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_ae0d_mac_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ae0d_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_ae0d_mac_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ae0d_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_ae0d_mac_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ae0d_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_ae0d_mac_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ae0d_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Data/en.525.612/Parlak_Project/hardware/ethernet_project/ethernet_project.gen/sources_1/bd/network_clock/ip/network_clock_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_ae0d_mac_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_ae0d_mac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
