@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Apr 03 10:52:37 -0400 2022
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim seg7_display_tb_behav -key {Behavioral:sim_1:Functional:seg7_display_tb} -tclbatch seg7_display_tb.tcl -protoinst "protoinst_files/bd_e836.protoinst" -protoinst "protoinst_files/echo_server.protoinst" -protoinst "protoinst_files/bd_574d.protoinst" -protoinst "protoinst_files/uart.protoinst" -log simulate.log"
call xsim  seg7_display_tb_behav -key {Behavioral:sim_1:Functional:seg7_display_tb} -tclbatch seg7_display_tb.tcl -protoinst "protoinst_files/bd_e836.protoinst" -protoinst "protoinst_files/echo_server.protoinst" -protoinst "protoinst_files/bd_574d.protoinst" -protoinst "protoinst_files/uart.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
